name: GMManager
main: minijaham\Main
api: 3.12.0
version: 1.0
author: minijaham
commands:
  gmc:
    description: "Change gamemode to Creative"
  gms:
    description: "Change gamemode to Survival"
  gma:
    description: "Change gamemode to Adventure"
  gmv:
    description: "Change gamemode to Spectator"
